import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Index.page/Header/Header";
import Main from "../components/Index.page/Main/Main";
import Footer from "../components/Index.page/Footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>yuto.page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main />

      <Footer />
    </div>
  );
}
