import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Index.page/Header/Header";
import Main from "../components/Index.page/Main/Main";
import Footer from "../components/Index.page/Footer/Footer";
import Contact_Main from "../components/Contact/ContactMain/Main";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>yuto_Contact.page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Contact_Main />

      <Footer />
    </div>
  );
}
