import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Index.page/Header/Header";
import Footer from "../components/Index.page/Footer/Footer";
import Works_Main from "../components/Works/WorksMain/Main";

export default function Works() {
  return (
    <div className={styles.container}>
      <Head>
        <title>yuto_Work.page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Works_Main />

      <Footer />
    </div>
  );
}
